@extends('layout.app')
@section('title','New Purchase Order')
@section('content')
<div class="page-head"><div><span class="eyebrow">PROCUREMENT</span><h1>New purchase order</h1><p class="muted">Select a supplier and add the products you intend to purchase.</p></div></div>
<div class="panel form-panel"><form method="POST" action="{{ route('purchase-orders.store') }}">@csrf
<div class="grid-2"><label>Supplier<select name="supplier_id" required><option value="">Select supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></label><label>Order date<input type="date" name="order_date" value="{{ old('order_date',now()->toDateString()) }}" required></label><label>Expected date<input type="date" name="expected_date"></label></div>
<div class="table-wrap"><table id="po-items"><thead><tr><th>Product</th><th>Quantity</th><th>Unit cost (UGX)</th><th></th></tr></thead><tbody><tr><td><select name="items[0][product_id]" required><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->product_name }} ({{ $product->sku }})</option>@endforeach</select></td><td><input type="number" name="items[0][quantity_ordered]" min="1" value="1" required></td><td><input type="number" name="items[0][unit_cost]" min="0" step="0.01" required></td><td><button type="button" class="btn btn-light remove-row">Remove</button></td></tr></tbody></table></div>
<button type="button" class="btn btn-light" id="add-row">＋ Add item</button><label>Notes<textarea name="notes" rows="4"></textarea></label><div class="form-actions"><a class="btn btn-light" href="{{ route('purchase-orders.index') }}">Cancel</a><button class="btn btn-primary">Create purchase order</button></div></form></div>
<script>let row=1;const body=document.querySelector('#po-items tbody');document.querySelector('#add-row').onclick=()=>{const tr=body.querySelector('tr').cloneNode(true);tr.querySelectorAll('input,select').forEach(el=>{el.name=el.name.replace(/items\[0\]/,'items['+row+']');if(el.tagName==='INPUT')el.value=el.type==='number'&&el.name.includes('quantity')?1:'';else el.selectedIndex=0});body.appendChild(tr);row++};body.addEventListener('click',e=>{if(e.target.classList.contains('remove-row')&&body.children.length>1)e.target.closest('tr').remove()});</script>
@endsection
