<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Your Cart — UJUZI SHOP MALL</title><link rel="stylesheet" href="{{ asset('css/app.css') }}"><link rel="stylesheet" href="{{ asset('css/storefront.css') }}"></head>
<body class="storefront"><header class="store-header"><div class="store-header-inner"><a class="store-logo" href="{{ route('marketplace.home') }}"><span>UZ</span><div><strong>UJUZI SHOP MALL</strong><small>Your shopping cart</small></div></a><nav class="store-actions"><a href="{{ route('marketplace.home') }}">Continue shopping</a>@guest<a href="{{ route('login') }}">Sign in</a>@endguest</nav></div></header>
<main class="store-section cart-page"><div class="section-heading"><div><span class="eyebrow">YOUR CART</span><h1>Ready when you are.</h1></div></div>
@if(session('success'))<div class="store-alert">{{ session('success') }}</div>@endif
@if($items)
<form method="POST" action="{{ route('cart.update') }}">@csrf<div class="cart-list">@foreach($items as $item)<div class="cart-row"><div class="cart-image">@if($item['product']->product_image)<img src="{{ asset('storage/images/'.$item['product']->product_image) }}" alt="{{ $item['product']->product_name }}">@else<div class="store-image-placeholder">UZ</div>@endif</div><div class="cart-info"><h3>{{ $item['product']->product_name }}</h3><span>{{ $item['product']->category }}</span><strong>UGX {{ number_format($item['lineTotal'],0) }}</strong></div><input class="cart-qty" type="number" name="items[{{ $item['product']->id }}]" value="{{ $item['quantity'] }}" min="1" max="{{ $item['product']->stock_quantity }}"><button class="remove-btn" type="submit" formaction="{{ route('cart.remove',$item['product']) }}" formmethod="POST">Remove</button></div>@endforeach</div><button class="store-btn secondary" type="submit">Update cart</button></form>
<div class="cart-summary"><span>Estimated total</span><strong>UGX {{ number_format($total,0) }}</strong>@guest<div class="checkout-gate"><strong>Ready to checkout?</strong><p>Your cart is saved while you browse. Create an account or sign in when you're ready to place your order.</p><div><a class="store-btn primary" href="{{ route('register') }}">Create account</a><a class="store-btn secondary" href="{{ route('login') }}">Sign in</a></div></div>@else@if(auth()->user()->isCustomer())<a class="store-btn primary" href="{{ route('checkout') }}">Continue to checkout</a>@endif@endguest</div>
@else<div class="empty-store"><h2>Your cart is empty.</h2><p>Browse the mall and add something you love.</p><a class="store-btn primary" href="{{ route('marketplace.home') }}">Start shopping</a></div>@endif
</main><footer class="store-footer"><strong>UJUZI SHOP MALL</strong><span>Shop from trusted businesses and retailers.</span></footer></body></html>
