<?php
namespace App\Http\Controllers;
use App\Models\Products;use App\Models\StockMovement;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Redirect;
class ProductController extends Controller {
 private function manager(Request $request):void{abort_unless($request->user()->isManager(),403);}
 public function index(Request $request){$products=Products::orderBy('product_name')->get();$totalProducts=$products->count();$totalStock=$products->sum('stock_quantity');$lowStock=$products->filter(fn($p)=>$p->is_low_stock)->count();$recentMovements=StockMovement::with(['product','user'])->latest()->limit(8)->get();return view('products.productList',compact('products','totalProducts','totalStock','lowStock','recentMovements'));}
 public function create(Request $request){$this->manager($request);return view('products.create');}
 public function store(Request $request){$this->manager($request);$data=$request->validate(['product_name'=>'required|string|max:255','sku'=>'required|string|max:100|unique:products,sku','description'=>'nullable|string','product_price'=>'required|numeric|min:0','cost_price'=>'nullable|numeric|min:0','category'=>'required|string|max:255','stock_quantity'=>'required|integer|min:0','reorder_level'=>'required|integer|min:0','product_image'=>'nullable|image|max:2048']);if($request->hasFile('product_image')){$data['product_image']=basename($request->file('product_image')->store('images','public'));}DB::transaction(function()use($data,$request){$product=Products::create($data);if($product->stock_quantity>0){StockMovement::create(['product_id'=>$product->id,'user_id'=>$request->user()->id,'type'=>'OPENING','quantity'=>$product->stock_quantity,'balance_before'=>0,'balance_after'=>$product->stock_quantity,'reason'=>'Opening stock']);}});return Redirect::route('products.index')->with('success','Product created successfully.');}
 public function edit(Request $request,$id){$this->manager($request);$product=Products::findOrFail($id);return view('products.edit',compact('product'));}
 public function update(Request $request,$id){$this->manager($request);$product=Products::findOrFail($id);$data=$request->validate(['product_name'=>'required|string|max:255','sku'=>['required','string','max:100','unique:products,sku,'.$product->id],'description'=>'nullable|string','product_price'=>'required|numeric|min:0','cost_price'=>'nullable|numeric|min:0','category'=>'required|string|max:255','stock_quantity'=>'required|integer|min:0','reorder_level'=>'required|integer|min:0','product_image'=>'nullable|image|max:2048']);if($request->hasFile('product_image')){$data['product_image']=basename($request->file('product_image')->store('images','public'));}$old=$product->stock_quantity;DB::transaction(function()use($product,$data,$old,$request){$product->update($data);$new=$product->stock_quantity;if($new!==$old){StockMovement::create(['product_id'=>$product->id,'user_id'=>$request->user()->id,'type'=>'ADJUSTMENT','quantity'=>abs($new-$old),'balance_before'=>$old,'balance_after'=>$new,'reason'=>'Manual product edit']);}});return Redirect::route('products.index')->with('success','Product updated successfully.');}
 public function delete(Request $request,$id){$this->manager($request);Products::findOrFail($id)->delete();return Redirect::route('products.index')->with('success','Product archived successfully.');}
 public function stockIn(Request $request,$id){$this->manager($request);$data=$request->validate(['quantity'=>'required|integer|min:1','reason'=>'nullable|string|max:255']);$product=Products::findOrFail($id);DB::transaction(function()use($product,$data,$request){$before=$product->stock_quantity;$product->increment('stock_quantity',$data['quantity']);StockMovement::create(['product_id'=>$product->id,'user_id'=>$request->user()->id,'type'=>'STOCK_IN','quantity'=>$data['quantity'],'balance_before'=>$before,'balance_after'=>$product->fresh()->stock_quantity,'reason'=>$data['reason']??'Stock received']);});return back()->with('success','Stock received successfully.');}
 public function stockOut(Request $request,$id){$this->manager($request);$data=$request->validate(['quantity'=>'required|integer|min:1','reason'=>'nullable|string|max:255']);$product=Products::findOrFail($id);if($data['quantity']>$product->stock_quantity)return back()->withErrors(['quantity'=>'Stock out quantity cannot exceed current stock.']);DB::transaction(function()use($product,$data,$request){$before=$product->stock_quantity;$product->decrement('stock_quantity',$data['quantity']);StockMovement::create(['product_id'=>$product->id,'user_id'=>$request->user()->id,'type'=>'STOCK_OUT','quantity'=>$data['quantity'],'balance_before'=>$before,'balance_after'=>$product->fresh()->stock_quantity,'reason'=>$data['reason']??'Stock issued']);});return back()->with('success','Stock issued successfully.');}
}
